name: reusable workflow
on: 
  workflow_call:
    inputs:
      node-version:
        description: 'Version of Node js to use'
        default: 'lts/*'
        required: false
        type: string
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: ${{ inputs.node-version }}
        - name: run test
          shell: bash
          run: |
            echo "node -v"
            echo "npm install"
            echo "npm test"
